project:
  type: website
  output-dir: _site

website:
  title: "KI Sommercamp 2025"
  description: "Techniques and Ethics of Generative AI"
  site-url: "https://denubis.github.io/KI-Summercamp-2025/"
  repo-url: "https://github.com/denubis/KI-Summercamp-2025"
  repo-actions: [edit, issue]
  
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: "Overview"
      - text: "Basic Course"
        menu:
          - text: "Week Overview"
            href: basic/index.qmd
          - text: "---"
          - text: "Day 1 - Control"
            menu:
              - text: "Session 1: Welcome"
                href: basic/day1-1.qmd
              - text: "Session 2: Confident Assistant"
                href: basic/day1-2.qmd
          - text: "Day 2 - Context"
            menu:
              - text: "Session 1: Basic Prompting"
                href: basic/day2-1.qmd
              - text: "Session 2: Metaprompting"
                href: basic/day2-2.qmd
          - text: "Day 3 - Verification"
            menu:
              - text: "Session 1: File Handling"
                href: basic/day3-1.qmd
              - text: "Session 2: Model Differences"
                href: basic/day3-2.qmd
          - text: "Day 4 - How Should We Work"
            menu:
              - text: "Session 1: Research Infrastructure"
                href: basic/day4-1.qmd
              - text: "Session 2: Boring Important Stuff"
                href: basic/day4-2.qmd
          - text: "Day 5 - Breaking Things"
            menu:
              - text: "Session 1: Systematic Failures"
                href: basic/day5-1.qmd
              - text: "Session 2: Synthesis"
                href: basic/day5-2.qmd
      - href: "https://www.uni-giessen.de/en/faculties/diml/media/aisummercamp2025/aisummercamp2025"
        text: "Official Page"
    right:
      - icon: github
        href: "https://github.com/YOUR-USERNAME/YOUR-REPO-NAME"
        aria-label: GitHub

  page-footer:
    left: |
      &copy; 2025 JLU Gießen | DiML | Dr. Brian Ballsun-Stanton | All site content CC-BY 4.0 International.
    center: |
      [Imprint](https://www.uni-giessen.de/impressum) | 
      [Privacy](https://www.uni-giessen.de/datenschutz)
    right: |
      Made with [Quarto](https://quarto.org/)

format:
  html:
    theme:
      light: [cosmo, theme-custom.scss]
      dark: [darkly, theme-custom-dark.scss]
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: right
    number-sections: false
    smooth-scroll: true
    code-fold: true
    code-summary: "Show code"
    code-tools:
      source: true
      toggle: true
      caption: none
    lang: en

execute:
  freeze: auto
  
revealjs:
  theme: [default, reveal-custom.scss]
  slide-number: true
  chalkboard: true
  preview-links: auto
  footer: "AI Summercamp 2025"