project:
  type: website
  output-dir: _site

website:
  title: "KI Sommercamp 2025"
  description: "Techniques and Ethics of Generative AI"
  site-url: "https://denubis.github.io/KI-Summercamp-2025/"
  repo-url: "https://github.com/denubis/KI-Summercamp-2025"
  repo-actions: [edit, issue]
  
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: "Overview"
      - text: "Basic Course"
        menu:
          - href: basic/day1.qmd
            text: "Day 1: Introduction"
      - text: "Advanced Course"
        menu:
          - href: advanced/day1.qmd
            text: "Day 1: Documentation & Coding"
      - href: "https://www.uni-giessen.de/en/faculties/diml/media/aisummercamp2025/aisummercamp2025"
        text: "Official Page"
    right:
      - icon: github
        href: "https://github.com/YOUR-USERNAME/YOUR-REPO-NAME"
        aria-label: GitHub

  page-footer:
    left: |
      &copy; 2025 JLU Gießen | DiML | Dr. Brian Ballsun-Stanton | All site content CC-BY 4.0 International.
    center: |
      [Imprint](https://www.uni-giessen.de/impressum) | 
      [Privacy](https://www.uni-giessen.de/datenschutz)
    right: |
      Made with [Quarto](https://quarto.org/)

format:
  html:
    theme:
      light: [cosmo, theme-custom.scss]
      dark: [darkly, theme-custom-dark.scss]
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: right
    number-sections: false
    smooth-scroll: true
    code-fold: true
    code-summary: "Show code"
    code-tools:
      source: true
      toggle: true
      caption: none
    lang: en

execute:
  freeze: auto
  
revealjs:
  theme: [default, reveal-custom.scss]
  slide-number: true
  chalkboard: true
  preview-links: auto
  footer: "AI Summercamp 2025"